#!/usr/bin/env node
import { existsSync } from 'node:fs';
/**
 * Combine site/ (static design doc) + preview/dist (built React app)
 * into a unified dist/ directory.
 *
 * dist/ is what gets deployed by Cloudflare. Two deploy modes are supported:
 *
 *   1. Cloudflare Pages: dashboard "Build output directory" = dist. Done.
 *   2. Cloudflare Workers (Workers Builds with assets):
 *      dashboard "Path" = dist; wrangler picks up the dist/wrangler.toml
 *      this script writes (which serves dist/ as static assets and avoids
 *      wrangler v4's pnpm-workspace-root detection error).
 */
import { cp, mkdir, rm, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const dist = resolve(root, 'dist');
const site = resolve(root, 'site');
const previewBuild = resolve(root, 'preview/dist');

if (!existsSync(previewBuild)) {
  console.error(
    `[build-dist] preview build missing at ${previewBuild}\nrun \`pnpm build:preview\` first`,
  );
  process.exit(1);
}

await rm(dist, { recursive: true, force: true });
await mkdir(dist, { recursive: true });

await cp(site, dist, { recursive: true });
await cp(previewBuild, resolve(dist, 'preview'), { recursive: true });

const wranglerToml = `# Generated by scripts/build-dist.mjs — do not edit by hand.
# Used only when deploying as a Cloudflare Worker (assets-only).
# For Cloudflare Pages, this file is ignored.
name = "manga-tracker"
compatibility_date = "2026-04-01"

[assets]
directory = "."
`;
await writeFile(resolve(dist, 'wrangler.toml'), wranglerToml, 'utf8');

console.log('[build-dist] dist/ assembled (site/ + preview/ + wrangler.toml)');
